version: "3"

services:
  backend:
    image: backend-img
    container_name: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8091:1080"
    volumes:
      - ./app:/app/

  queue:
    image: dr2.parswitch.com/devops/rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"

  celery-worker:
    image: celery-img
    container_name: celery
    restart: always
    depends_on:
      - backend
      - queue
    env_file:
      - .env
    build:
      context: .
      dockerfile: celeryworker.dockerfile

  rocketry-worker:
    image: rocketry-img
    container_name: rocketry
    build:
      context: .
      dockerfile: rocketryscheduler.dockerfile
    volumes:
      - ./app:/app/
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
