version: "3.7"
services:
  db:
    image: dr.parswitch.com/postgres:14
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data

  redis:
    image: dr.parswitch.com/redis:7.0.5
    restart: always
    ports:
      - 6379:6379