"""empty message

Revision ID: c39d5f4bc3eb
Revises: dd8847266e7f
Create Date: 2024-12-23 07:06:28.284577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39d5f4bc3eb'
down_revision = 'dd8847266e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
